### ISSUE TITLE
example for assume_aligned does not compile

### ISSUE THREAD

**Issue by TyRoXx** [glenfe/align#6]
This is one of the tutorials (http://www.boost.org/doc/libs/1_60_0/doc/html/align/tutorial.html#align.tutorial.assume_aligned):
```C++
#include <boost/align/assume_aligned.hpp>

void use(double* array, std::size_t size)
{
    BOOST_ALIGN_ASSUME_ALIGNED(array, 16);
    for (std::size_t i = 0; i < size; i++) {
        array[i]++;
    }
}

int main()
{
    alignas(16) double d[4] { };
    use(d, 4);
}
```

The following error was observed with GCC 4.8 on Ubuntu AMD64 and Boost 1.60:
```
error: invalid conversion from 'void*' to 'double*' [-fpermissive]
     BOOST_ALIGN_ASSUME_ALIGNED(array, 16);
     ^
```

The reference (http://www.boost.org/doc/libs/1_60_0/doc/html/align/reference.html#align.reference.assume_aligned) does not say that the macro only works for void pointers, so I assume that the mistake is in the implementation:
```C++
#define BOOST_ALIGN_ASSUME_ALIGNED(ptr, alignment) \
(ptr) = __builtin_assume_aligned((ptr), (alignment))
```

``__builtin_assume_aligned`` will always return a void pointer, so this assignment can only work if the original ``ptr`` is a void pointer.

It looks like Boost.Align only tests ``BOOST_ALIGN_ASSUME_ALIGNED`` with void pointers (https://github.com/glenfe/align/blob/1f829685e08d4c6b8c96e08b043bf8e03d27ae49/test/assume_aligned_test.cpp).

My workaround is to cast my non-void pointers to void pointers when I pass them to ``BOOST_ALIGN_ASSUME_ALIGNED``. When I actually use them, I cast the pointers back to what they actually are. Optimizations should still apply, but my code is now full of unnecessary void pointers.

**Comment by glenfe** [comment]
Thanks! I've updated the implementation for GCC.
