### ISSUE TITLE
Is there a facility to allocate an array of aligned objects?

### ISSUE THREAD

**Issue by NickStrupat** [glenfe/align#7]
`boost::alignment::aligned_allocator` appears to allocate aligned memory for `T`s but how can we create an array of `T` where each `T` is aligned.

For example, say you want each element on it's own cache line to avoid false sharing in a highly contested queue. Can the `Allocator` concept be implemented to provide that functionality?

**Comment by glenfe** [comment]
You can use `boost::alignment::aligned_allocator` to allocate storage for more than a single object. The first parameter of `allocate()` is the count of objects, and you can supply a value greater than `1`.

**Comment by NickStrupat** [comment]
Right, but only the storage memory block is aligned. The `T`s are not aligned (well, the first one would be).

I realized that we need to use a wrapped `T` with its own alignment to achieve that...

```cpp
template<typename T, std::size_t Alignment>
struct aligned {
    T alignas(Alignment) value;
};

#include <vector>
#include <boost/align/aligned_allocator.hpp>

template<typename T, std::size_t Alignment = 64>
using aligned_vector = std::vector<aligned<T, Alignment>, boost::alignment::aligned_allocator<aligned<T, Alignment>, Alignment>>;

aligned_vector<int> v; // all elements are `aligned<int>` and all `T`s are aligned to `Alignment` of 64
```

This example effectively puts each element on its own cache line (on architectures with a cache line size of 64).

**Comment by glenfe** [comment]
They all are aligned for `T`, assuming you construct them in the right locations. Size of a type is always a multiple of alignment. If the first object (occupying `sizeof(T)` bytes), constructed at `&storage[0]`, is aligned for `alignof(T)`, then the next object, constructed at `&storage[1]` is also aligned for `alignof(T)`.

**Comment by glenfe** [comment]
I think you're saying that in your case `alignof(T)` is less than the alignment that you want each T object aligned on. In that case, yes, define a new type like you suggested.
